name: milkapis_sdk_dart
description: A dart sdk for milkapis.
version: 0.0.18
repository: https://github.com/milkhq/milkapis_sdk_dart
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  firedart: ^0.9.7
  shared_preferences: ^2.2.2
  # firebase_auth: ^4.10.0
  # firebase_core: ^2.16.0
  # milkapis_client_dart:
    # path: /Users/pl/Documents/milkhq/milkapis_protobuf/src/generated/dart
  milkapis_client_dart:
    git:
      url: https://github.com/milkhq/milkapis_protobuf.git
      ref: milkapis_protobuf-v0.0.27
      path: src/generated/dart
  get_it: ^7.6.4
  grpc: ^3.2.4
  pool: ^1.5.1
  rxdart: ^0.27.2

dependency_overrides: 
  grpc: 
    path: /Users/pl/Documents/open-source/forks/grpc-dart

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
