name: milkapis_sdk_dart
description: A dart sdk for milkapis.
version: 0.0.0
repository: https://github.com/milkhq/milkapis_sdk_dart

environment:
  sdk: ^3.2.0-190.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
