name: Create Release(s)

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - uses: actions/checkout@v3
      # - name: Setup git
      #   env:
      #     PAT: ${{ secrets.BOT_ACCESS_TOKEN }}
      #   run: |
      #     git config user.name "Powntheep Laokhunthot"
      #     git config user.email "powntheep@milk.build"
      - uses: bluefireteam/melos-action@v2
      - name: List changes
        run: git log
      - name: List packages
        run: melos list
      - name: Create the new version(s)
        run: melos version --all --yes
      - name: Push created version commit
        run: git push
      - name: Push modified tags
        run: git push --tags
